#!/bin/bash -l
# Bash is needed because we use its "array" data structure
# the -l flag means it will act like a login shell,
# and source the .profile, .bashrc, and so on

# List of all tasks to execute
tasks=(
'python patch_mlp_test_save_patches.py'
)

# Execute the task
${tasks[$PBS_ARRAYID]}
